[providers]
bun = "1.3"

[phases.setup]
nixPkgs = ["bun"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "cd backend && bun install || bun install"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "echo 'Build complete'"
]

[start]
cmd = "cd backend && bun run src/server.js"
