[providers]
bun = "1.3"

[phases.setup]
nixPkgs = ["bun"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "bun install"
]

[phases.build]
dependsOn = ["install"]

[start]
cmd = "bun run src/server.js"
