[providers]
node = "18"

[variables]
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "rm -f bun.lockb || true",
    "npm install"
]

[phases.build]
dependsOn = ["install"]

[start]
cmd = "npm start"
