[providers]
node = "18"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "npm install"
]

[phases.build]
dependsOn = ["install"]

[start]
cmd = "npm start"
